### PR TITLE
Create onion.md

### PR DESCRIPTION
**Pull request by asgh**

### CODE REVIEW

**Comment by navarr** [comment]
Am wondering if the action of "sautéing" should be a pattern?  Kind of like a function?

**Comment by appplemac** [comment]
Hey @asgh, thank you so much for submitting this!

I would have to agree with @navarr – I think this is a little too much of a low-level concept. A vegetable sauté in general, though, looks more like a pattern in this context. What do you think, @asgh?

**Comment by asgh** [comment]
You article mentioned how once you know "patterns" you can put together all sorts of dishes.

That's exactly what this is: Once you know this you can add so many different things and have a delicious dish without needing a recipe.

I don't think your intent is making a list of simple core basic recipes (if I'm wrong tell me), but rather the building blocks of other recipes, and this is one of them.

@navarr The action of sautéing is a cooking technique, it's not a building block that you can add food on top of. It's a way of cooking the food. To me that seems different, but maybe I have not understood the idea of this git.

**Comment by appplemac** [comment]
@asgh Got your point, let me think about it for a while – I will get back to this tomorrow. Cheers!

**Comment by appplemac** [comment]
@asgh Just had some sautéed onions with my mother’s [varenyky](http://en.wikipedia.org/wiki/Varenyky), and I get your point even better.

**Pull request merged**
