### PR TITLE
Added a recipe for baked potatoes

### PR DESCRIPTION
**Pull request by gausby**
Baked potatoes. Burning hot!

### CODE REVIEW

**Comment by appplemac** [comment]
Hey @gausby, well done, thanks so much for submitting this!

I am a little worried, though, that this is closer to being a recipe than a pattern. From what I know, baking as a technique can only be applied to potatoes but not other vegetables – for all the rest it would be roasting rather than baking, and that is a fundamental difference (you can roast the potatoes as well, I know). Therefore you cannot really apply this kind of preparation to anything else but potatoes.

What do you think? Is this a pattern that allows enough variations? Would love to hear your opinion. Cheers!

**Comment by gausby** [comment]
Hmm, I guess any kind of root vegetable can be prepared in the same way. Of course, the vegetable have to be sizeable—as it goes with potatoes as well, some potatoes does not lent itself to this technique, as they would turn into charcoal if they are too small.

Beetroots and celeriac would be good candidates for this technique.

**Comment by andredublin** [comment]
Oven roasting or baking would be the high level pattern, where as baking a potato is more low level.
This would serve well as a recipe under said pattern.

**Comment by agryson** [comment]
Comparativley, it seems that roasting and baking both fall under dry heat cooking methods. However, according to http://www.reluctantgourmet.com/baking-or-roasting-you-decide/ it would seem that:

"Baking" is more for foodstuffs that will change form, (a batter that becomes a cake, a dough that becomes bread) a food that changes form through the generation of air and steam as is the case with potatoes.
"Roasting" is more for cooking a food with the intention of a particular surface finish, generally through the application of oil, butter, grease or other shortenings to replicate the original finish of 'roasting' (which in days of yore was over an open flame)

**Comment by appplemac** [comment]
Alright, maybe this pattern could be promoted to “oven-baked vegetables”?

**Pull request closed without merging**
